### ISSUE TITLE
my issue title 

### ISSUE THREAD

**Issue by rsharifnasab** [amirhallaji/OS-Project#1]
---

**name:** my problem report 
**about:** about the problem a bit more
**title:** my issue title 
**lables:** wow, serious bug

**Explaining the problem**:
my problem is ... 

**How did it happen**
didn't happened yet, but in case

**What did you explain**
hmm?

**Place screenshot here**
ok

**your OS**
**linux**, with honor

**Extra information**
this is a great issue template

**Comment by amirhallaji** [comment]
Issue_template worked successfully.😂😂

**Comment by rsharifnasab** [comment]
OK then! 
thank you so much

**Comment by amirhallaji** [comment]
You're welcome.
